name: MIPS Build for CR6606

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Stable Rust
        # 这一步只安装宿主机编译环境，不再纠结 MIPS 的 std
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        run: cargo install cross --git https://github.com/cross-rs/cross.git

      - name: Build Starship
        # cross 会自动进入 messense 镜像寻找它自带的 MIPS std
        run: |
          cross build --release --target mipsel-unknown-linux-musl
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"

      - name: Post Process (Strip)
        run: |
          docker run --rm -v $(pwd):/work -w /work \
          messense/rust-musl-cross:mipsel-musl \
          mipsel-linux-musl-strip target/mipsel-unknown-linux-musl/release/starship

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: starship-mipsel-cr6606
          path: target/mipsel-unknown-linux-musl/release/starship
